# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: robjefferson.uk
email: robjjdn15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Rob Jefferson, Web & Creative Services Business Partner for Doncaster Council.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.robjefferson.uk" # the base hostname & protocol for your site
twitter_username: robjefferson
github_username: rob-jefferson

# Build settings
markdown: kramdown
